// Document categories and subcategories based on database schema
export const DOCUMENT_CATEGORIES = {
  Hansards: [
    "Hansards 2025",
    "Hansards 2024",
    "Hansards 2023",
    "Hansards 2022",
    "Hansards 2021",
    "Hansards 2020",
    "Hansards 2019",
    "Hansards 2018",
    "Hansards 2017",
    "Hansards 2016",
    "Hansards 2015",
    "Hansards 2014",
    "Hansards 2013",
    "Hansards 2012",
    "Hansards 2011",
    "Hansards 2010",
    "Hansards 2009",
    "Hansards 2008",
    "Hansards 2007",
    "Hansards 2006",
    "Hansards 2005",
    "Hansards 2004",
    "Hansards 2003",
    "Hansards 2002",
    "Hansards 2001",
    "Hansards 2000",
    "Hansards 1999",
    "Hansards 1998",
    "Hansards 1997",
    "Hansards 1996",
    "Hansards 1995",
    "Hansards 1994",
    "Hansards 1993",
    "Hansards 1992",
    "Hansards 1991",
    "Hansards 1990",
    "Hansards 1989",
    "Hansards 1988",
    "Hansards 1987",
    "Hansards 1986",
    "Hansards 1985",
    "Hansards 1984",
    "Hansards 1983",
    "Hansards 1982",
    "Hansards 1981",
    "Hansards 1980",
    "Hansards 1979",
    "Hansards 1978",
    "Hansards 1977",
    "Hansards 1976",
    "Hansards 1975",
    "Hansards 1974",
    "Hansards 1973",
    "Hansards 1972",
    "Hansards 1971",
    "Hansards 1970",
    "Hansards 1969",
    "Hansards 1968",
    "Hansards 1967",
    "Hansards 1966",
    "Hansards 1965",
    "Hansards 1964",
    "Hansards 1963",
    "Hansards 1962",
    "Hansards 1961",
    "Hansards 1960",
    "Hansards 1959",
    "Hansards 1958",
    "Hansards 1957",
    "Hansards 1956",
  ],
  "Courts of Record": [
    "Supreme Court of Uganda",
    "Court of Appeal of Uganda",
    "Constitutional Court of Uganda",
    "High Court of Uganda",
    "High Court of Uganda/Commercial Court Division",
    "High Court of Uganda/Anti-Corruption Division",
    "High Court of Uganda/Civil Division",
    "High Court of Uganda/Criminal Division",
    "High Court of Uganda/Family Division",
    "High Court of Uganda/International Crimes Division",
    "High Court of Uganda/Land Division",
    "High Court of Uganda/Industrial Court Division",
    "High Court of Uganda/Election Petitions",
  ],
  "State Tribunals": [
    "Center for Arbitration and Dispute Resolution of Uganda",
    "Equal Opportunities Commission",
    "Insurance Appeals Tribunal (Uganda)",
    "Leadership Code Tribunal of Uganda",
    "Public Procurement and Disposal of Public Assets Appeals Tribunal",
    "Tax Appeals Tribunal (Uganda)",
  ],
  "Acts of Parliament": ["Acts of Parliament"],
  "Legal Notices": ["Legal Notices"],
  Ordinances: ["Ordinances"],
  "Statutory Instruments": [
    "Statutory Instruments 2001",
    "Statutory Instruments 2002",
    "Statutory Instruments 2003",
    "Statutory Instruments 2004",
    "Statutory Instruments 2005",
    "Statutory Instruments 2006",
    "Statutory Instruments 2007",
    "Statutory Instruments 2008",
    "Statutory Instruments 2009",
    "Statutory Instruments 2010",
    "Statutory Instruments 2011",
    "Statutory Instruments 2012",
    "Statutory Instruments 2013",
    "Statutory Instruments 2014",
    "Statutory Instruments 2015",
    "Statutory Instruments 2016",
    "Statutory Instruments 2017",
    "Statutory Instruments 2018",
    "Statutory Instruments 2019",
    "Statutory Instruments 2020",
    "Statutory Instruments 2021",
    "Statutory Instruments 2022",
    "Statutory Instruments 2023",
    "Statutory Instruments 2024",
    "Statutory Instruments 2025",
    "Statutory Instruments 2026",
  ],
  Gazettes: [
    "Gazzetes 2025",
    "Gazzetes 2024",
    "Gazzetes 2023",
    "Gazzetes 2022",
    "Gazzetes 2021",
    "Gazzetes 2020",
    "Gazzetes 2019",
    "Gazzetes 2018",
    "Gazzetes 2017",
    "Gazzetes 2016",
    "Gazzetes 2015",
    "Gazzetes 2014",
    "Gazzetes 2013",
    "Gazzetes 2012",
    "Gazzetes 2011",
    "Gazzetes 2010",
    "Gazzetes 2009",
    "Gazzetes 2008",
    "Gazzetes 2007",
    "Gazzetes 2006",
    "Gazzetes 2005",
    "Gazzetes 2004",
    "Gazzetes 2003",
    "Gazzetes 2002",
    "Gazzetes 2001",
    "Gazzetes 2000",
    "Gazzetes 1999",
    "Gazzetes 1998",
    "Gazzetes 1997",
    "Gazzetes 1996",
    "Gazzetes 1995",
    "Gazzetes 1994",
    "Gazzetes 1993",
    "Gazzetes 1992",
    "Gazzetes 1991",
    "Gazzetes 1990",
    "Gazzetes 1989",
    "Gazzetes 1988",
    "Gazzetes 1987",
    "Gazzetes 1986",
    "Gazzetes 1985",
    "Gazzetes 1984",
    "Gazzetes 1983",
    "Gazzetes 1982",
    "Gazzetes 1981",
    "Gazzetes 1980",
    "Gazzetes 1979",
    "Gazzetes 1978",
    "Gazzetes 1977",
    "Gazzetes 1976",
    "Gazzetes 1975",
    "Gazzetes 1974",
    "Gazzetes 1973",
    "Gazzetes 1972",
    "Gazzetes 1971",
    "Gazzetes 1970",
    "Gazzetes 1969",
    "Gazzetes 1968",
    "Gazzetes 1967",
    "Gazzetes 1966",
    "Gazzetes 1965",
    "Gazzetes 1964",
    "Gazzetes 1963",
    "Gazzetes 1962",
    "Gazzetes 1961",
    "Gazzetes 1960",
    "Gazzetes 1959",
    "Gazzetes 1958",
    "Gazzetes 1957",
    "Gazzetes 1956",
    "Gazzetes 1955",
    "Gazzetes 1954",
    "Gazzetes 1953",
    "Gazzetes 1952",
    "Gazzetes 1951",
    "Gazzetes 1950",
    "Gazzetes 1949",
    "Gazzetes 1948",
    "Gazzetes 1947",
    "Gazzetes 1946",
    "Gazzetes 1945",
    "Gazzetes 1944",
    "Gazzetes 1943",
    "Gazzetes 1942",
    "Gazzetes 1941",
    "Gazzetes 1940",
    "Gazzetes 1939",
    "Gazzetes 1938",
    "Gazzetes 1937",
    "Gazzetes 1936",
    "Gazzetes 1935",
    "Gazzetes 1934",
    "Gazzetes 1933",
    "Gazzetes 1932",
    "Gazzetes 1931",
    "Gazzetes 1930",
    "Gazzetes 1929",
    "Gazzetes 1928",
    "Gazzetes 1927",
    "Gazzetes 1926",
    "Gazzetes 1925",
    "Gazzetes 1924",
    "Gazzetes 1923",
    "Gazzetes 1922",
    "Gazzetes 1921",
    "Gazzetes 1920",
    "Gazzetes 1919",
    "Gazzetes 1918",
    "Gazzetes 1917",
    "Gazzetes 1916",
    "Gazzetes 1915",
    "Gazzetes 1914",
    "Gazzetes 1913",
    "Gazzetes 1912",
    "Gazzetes 1911",
    "Gazzetes 1910",
    "Gazzetes 1909",
    "Gazzetes 1908",
    "Gazzetes 1907",
    "Gazzetes 1906",
    "Gazzetes 1905",
    "Gazzetes 1904",
    "Gazzetes 1903",
    "Gazzetes 1902",
    "Gazzetes 1901",
    "Gazzetes 1900",
  ],
  "Archival Materials": ["Archival Materials"],
  "Legal Forms": [
    "Court Forms",
    "Company Forms",
    "Land Forms",
    "Immigration Forms",
    "Tax Forms",
  ],
  "Practice Directions": [
    "Supreme Court",
    "Court of Appeal",
    "High Court",
    "Specialized Divisions",
  ],
  "Law Reports": [
    "Uganda Law Reports",
    "East African Law Reports",
    "Human Rights Law Reports",
  ],
  "Legal Commentaries": [
    "Case Commentaries",
    "Legislative Guides",
    "Practice Notes",
    "Legal Updates",
  ],
};

export const DOCUMENT_TYPES = {
  "application/pdf": {
    label: "PDF Document",
    icon: "FileText",
    extensions: [".pdf"],
  },
  "application/msword": {
    label: "Word Document",
    icon: "FileText",
    extensions: [".doc"],
  },
  "application/vnd.openxmlformats-officedocument.wordprocessingml.document": {
    label: "Word Document",
    icon: "FileText",
    extensions: [".docx"],
  },
  "text/plain": {
    label: "Text Document",
    icon: "FileText",
    extensions: [".txt"],
  },
  "application/rtf": {
    label: "Rich Text Document",
    icon: "FileText",
    extensions: [".rtf"],
  },
  "application/vnd.ms-excel": {
    label: "Excel Spreadsheet",
    icon: "FileText",
    extensions: [".xls"],
  },
  "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet": {
    label: "Excel Spreadsheet",
    icon: "FileText",
    extensions: [".xlsx"],
  },
};

export const DOCUMENT_STATUSES = {
  active: {
    label: "Active",
    color: "green",
    description: "Document is available and accessible",
  },
  archived: {
    label: "Archived",
    color: "gray",
    description: "Document has been archived",
  },
  draft: {
    label: "Draft",
    color: "yellow",
    description: "Document is in draft state",
  },
  processing: {
    label: "Processing",
    color: "blue",
    description: "Document is being processed",
  },
};

export const DOCUMENT_SORT_OPTIONS = [
  { value: "created_at", label: "Date Created" },
  { value: "title", label: "Title" },
  { value: "category", label: "Category" },
  { value: "metadata.size", label: "Size" },
];

export const formatFileSize = (bytes: number): string => {
  if (bytes === 0) return "0 Bytes";
  const k = 1024;
  const sizes = ["Bytes", "KB", "MB", "GB"];
  const i = Math.floor(Math.log(bytes) / Math.log(k));
  return `${parseFloat((bytes / Math.pow(k, i)).toFixed(2))} ${sizes[i]}`;
};

export const getDocumentTypeFromExtension = (filename: string): string => {
  const extension = filename.split(".").pop()?.toLowerCase();
  for (const [mimeType, info] of Object.entries(DOCUMENT_TYPES)) {
    if (info.extensions.includes(`.${extension}`)) {
      return mimeType;
    }
  }
  return "application/octet-stream";
};

export const isValidDocumentType = (type: string): boolean => {
  return type in DOCUMENT_TYPES;
};
